### ISSUE TITLE
Heroku. Fix deploy problems

### ISSUE THREAD

**Issue by dpolevodin** [alenasaz/js-school-project#25]
Не деплоится проект на хероку, ошибка Memory exceed
#buildpack

**Comment by alenasaz** [comment]
@dpolevodin, а это же могу закрыть уже?

**Comment by dpolevodin** [comment]
@alenasaz конечно)

**Comment by alenasaz** [comment]
Поменяла buildpack в settings
https://github.com/mars/create-react-app-buildpack.git и проблема решилась
